services:
  s1-database:
    image: mongo:7.0.0
    container_name: s1-database
    hostname: database.s1.pdn
    restart: always
    ports:
      - ${DB_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./mongodb/config/mongod.conf:/etc/mongod.conf
      - ./mongodb/data/log/:/var/log/mongodb
      - ./mongodb/data/volume:/var/lib/mongodb
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    command: ['-f', '/etc/mongod.conf']
  s1-oauth:
    #use -dev for check data set in .env its correct.
    image: pdnmx/s1-oauth:1.0-prod
    container_name: s1-oauth
    hostname: oauth.s1.pdn
    restart: always
    ports:
      - ${API_OAUTH_PORT}:3000
    environment:
      JWT_SECRET: ${JWT_SECRET}
      JWT_AUDIENCE: ${JWT_AUDIENCE}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_TOKEN_TTL: ${JWT_TOKEN_TTL}
      JWT_REFRESH_TOKEN_TTL: ${JWT_REFRESH_TOKEN_TTL}
      API_OAUTH_PREFIX: ${API_OAUTH_PREFIX}
      MONGO_OAUTH_HOST: ${MONGO_OAUTH_HOST}
      MONGO_OAUTH_USER: ${MONGO_OAUTH_USER}
      MONGO_OAUTH_PASS: ${MONGO_OAUTH_PASS}
      MONGO_OAUTH_PORT: ${MONGO_OAUTH_PORT}
      MONGO_OAUTH_DATABASE: ${MONGO_OAUTH_DATABASE}
      MONGO_OAUTH_DB_AUTH: ${MONGO_OAUTH_DB_AUTH}
  s1-api:
    #use -dev for check data set in .env its correct.
    image: pdnmx/s1-api:1.1-prod
    container_name: s1-api
    hostname: api.s1.pdn
    restart: always
    ports:
      - ${API_S1_PORT}:4000
    environment:
      JWT_SECRET: ${JWT_SECRET}
      JWT_AUDIENCE: ${JWT_AUDIENCE}
      JWT_ISSUER: ${JWT_ISSUER}
      API_S1_PREFIX: ${API_S1_PREFIX}
      MONGO_S1_HOST: ${MONGO_S1_HOST}
      MONGO_S1_USER: ${MONGO_S1_USER}
      MONGO_S1_PASS: ${MONGO_S1_PASS}
      MONGO_S1_PORT: ${MONGO_S1_PORT}
      MONGO_S1_DATABASE: ${MONGO_S1_DATABASE}
      MONGO_S1_DB_AUTH: ${MONGO_S1_DB_AUTH}
